// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bezmxockiownontvryzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlem14b2NraW93bm9udHZyeXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTUzMTgsImV4cCI6MjA2NzEzMTMxOH0.LXJ2FeZjfOgdBrGErgzWgZdb6Md2WZL3XA4gyiFp8lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});